# action.yml
name: 'AutML Workflow'
description: 'Automated Machine Learning inside Github Actions'
branding:
  icon: 'bar-chart'  
  color: 'green'
inputs:
  dataset:  
    description: 'Data URL.'
    required: true
  target:  
    description: 'The target variable.'
    required: true
  when:
    description: 'The data that you want to make a prediction for.'
    required: true
  stop_training:
    description: 'Stop training after X seconds.'
    required: false
outputs:
  prediction:
    description: 'Predicted value'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.dataset }}
    - ${{ inputs.target }}
    - ${{ inputs.when }}
    - ${{ inputs.stop_training }}
